import nodemailer from "nodemailer";
import { NextResponse } from "next/server";

export async function POST(request) {
  // 1. Log that a request has hit the endpoint
  console.log("=== [SERVER LOG] Incoming Contact Form Request Received ===");

  try {
    const body = await request.json();
    const { name, email, phone, subject, message } = body;

    // 2. Log payload receipt for visibility
    console.log(
      `[SERVER LOG] Data Payload: Name="${name}", Email="${email}", Subject="${subject}"`,
    );

    // Basic validation
    if (!name || !email || !message) {
      console.warn(
        "[SERVER LOG] Validation Failed: Missing required fields (name, email, or message).",
      );
      return NextResponse.json(
        { message: "Name, email and message are required." },
        { status: 400 },
      );
    }

    // 3. Diagnostic Log: Check if environment variables are actually loading
    console.log("[SERVER LOG] Environment Variable Verification:");
    console.log(
      ` -> SMTP_USER: ${process.env.SMTP_USER ? `✅ Loaded (${process.env.SMTP_USER})` : "❌ UNDEFINED"}`,
    );
    console.log(
      ` -> SMTP_PASS: ${process.env.SMTP_PASS ? "✅ Loaded (Protected Password String)" : "❌ UNDEFINED"}`,
    );

    if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
      console.error(
        "[SERVER LOG] Crucial authentication variables are missing from your environment config!",
      );
    }

    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    // 4. Diagnostic Handshake: Test Gmail connection pool authentication
    console.log(
      "[SERVER LOG] Performing secure SMTP handshake verification with Gmail...",
    );
    try {
      await transporter.verify();
      console.log(
        " -> SMTP Verification Handshake: ✅ SUCCESS! Connection credentials authenticated.",
      );
    } catch (verifyError) {
      console.error(
        " -> SMTP Verification Handshake: ❌ FAILED! Credentials rejected by Google server.",
      );
      console.error(` -> Details: ${verifyError.message}`);
      // Throwing error early to bounce down to the catch matrix cleanly
      throw verifyError;
    }

    // 5. Fire the actual email payload out
    console.log("[SERVER LOG] Attempting delivery of the email envelope...");
    const mailInfo = await transporter.sendMail({
      from: `"SHAFA Contact" <${process.env.SMTP_USER}>`,
      replyTo: email,
      to: process.env.SMTP_USER,
      subject: subject || `New message from ${name}`,
      text: `
Name: ${name}
Email: ${email}
Phone: ${phone || "—"}
Subject: ${subject || "—"}

Message:
${message}
      `.trim(),
      html: `
        <div style="font-family: Georgia, serif; color: #333; line-height: 1.6;">
          <p><strong>Name:</strong> ${name}</p>
          <p><strong>Email:</strong> ${email}</p>
          <p><strong>Phone:</strong> ${phone || "—"}</p>
          <p><strong>Subject:</strong> ${subject || "—"}</p>
          <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;" />
          <p><strong>Message:</strong></p>
          <p style="white-space: pre-wrap;">${message}</p>
        </div>
      `,
    });

    // 6. Log successful receipt ID generated by node connection loop
    console.log(
      `[SERVER LOG] Delivery: ✅ SUCCESS! Email accepted by Gmail relay with ID: ${mailInfo.messageId}`,
    );
    console.log("=======================================================\n");

    return NextResponse.json({ message: "Message sent successfully" });
  } catch (error) {
    // 7. Comprehensive Error Catching Block
    console.error("================ [SERVER LOG ERROR] ===================");
    console.error("❌ Email process failed on the server layer.");
    console.error(` -> Error Name: ${error.name}`);
    console.error(` -> Error Message: ${error.message}`);
    if (error.stack) {
      console.error(" -> System Stack Trace:");
      console.error(error.stack);
    }
    console.error("=======================================================\n");

    return NextResponse.json(
      { message: `Failed to send message: ${error.message}` },
      { status: 500 },
    );
  }
}
